FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["BffService.csproj", "./"]
RUN dotnet restore "BffService.csproj"
COPY . .
RUN dotnet build "BffService.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "BffService.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "BffService.dll"]
