upstream gifts_upstream {
    server gifts-service-1:8080;
    server gifts-service-2:8080;
}

server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html/browser;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/Auth {
        proxy_pass http://auth-service:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/Gifts {
        proxy_pass http://gifts_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        add_header X-Served-By $upstream_addr;
    }

    location /api/Donor {
        proxy_pass http://gifts_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/Inventory {
        proxy_pass http://inventory-service:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/Orders {
        proxy_pass http://orders-service:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/bff {
        proxy_pass http://bff-service:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
